import Head from "next/head";
import Image from 'next/image';
import nobelsetLogo from "@assets/img/header-logo.png"

const SEO = ({pageTitle}) => (
  <>
    <Head>
      <title>
        {pageTitle && `${pageTitle} - NOBLE SETS`}
      </title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta name="robots" content="noindex, follow" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link rel="icon" href="/favicon.png" />
      <Image src={nobelsetLogo} alt="logo" />
    </Head>
  </>
);

export default SEO;